name: Build Custom Image

on:
  workflow_dispatch:
  push:
    branches:
        - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout webapp
      uses: actions/checkout@v2

    - name: Create .env file with zip artifact
      run: |
        echo "USER= ${{ secrets.SQL_USER }}" >> .env
        echo "DATABASE=${{ secrets.DATABASE }}" >> .env
        echo "PASSWORD=${{ secrets.SQL_PSWD}}" >> .env
        echo "HOST=127.0.0.1" >> .env
        echo "DIALECT=mysql" >> .env
        echo "AUTH_USER=${{ secrets.AUTH_USER }}" >> .env
        echo "AUTH_PSWD=${{ secrets.AUTH_PSWD }}" >> .env
        zip -r /tmp/webapp.zip .env .

    - name: Upload repository artifact
      uses: actions/upload-artifact@v2
      with:
        name: webapp-artifact
        path: /tmp/webapp.zip

    - name: Download webapp artifact
      uses: actions/download-artifact@v2
      with:
        name: webapp-artifact
    
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
          version: '>= 363.0.0'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Initialize Packer
      run:  packer init packer/packer_file.pkr.hcl
    
    - name: Format Packer configuration
      run:  packer fmt packer/packer_file.pkr.hcl
    
    - name: Validate Packer configuration
      run:  packer validate packer/packer_file.pkr.hcl
          
    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: Run Packer Build
      run: packer build packer/packer_file.pkr.hcl
