name: Build Custom Image

on:
  workflow_dispatch:
  push:
    branches:
        - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout webapp
      uses: actions/checkout@v2

    - name: Create .sh file with zip artifact
      run: |
        echo "export SQL_USER=${{ secrets.SQL_USER }}" >> envSetup.sh
        echo "export TESTUSER=${{ secrets.SQL_USER }}" >> envSetup.sh
        echo "export DATABASE=${{ secrets.DATABASE }}" >> envSetup.sh
        echo "export SQL_PSWD=${{ secrets.SQL_PSWD }}" >> envSetup.sh
        echo "export HOST=127.0.0.1" >> envSetup.sh
        echo "export DIALECT=mysql" >> envSetup.sh
        echo "export AUTH_USER=${{ secrets.AUTH_USER }}" >> envSetup.sh
        echo "export AUTH_PSWD=${{ secrets.AUTH_PSWD }}" >> envSetup.sh

        echo "#!/bin/bash" > start_webapp.sh
        echo "source ./envSetup.sh" >> start_webapp.sh
        echo "npm start" >> start_webapp.sh

        zip -r /tmp/webapp.zip envSetup.sh start_webapp.sh

    - name: Upload repository artifact
      uses: actions/upload-artifact@v2
      with:
        name: webapp-artifact
        path: /tmp/webapp.zip

    - name: Download webapp artifact
      uses: actions/download-artifact@v2
      with:
        name: webapp-artifact
    
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
          version: '>= 363.0.0'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: Initialize Packer
      run:  packer init packer/packer_file.pkr.hcl
    
    - name: Format Packer configuration
      run:  packer fmt packer/packer_file.pkr.hcl
    
    - name: Validate Packer configuration
      run:  packer validate packer/packer_file.pkr.hcl
          
    - name: Run Packer Build
      run: packer build packer/packer_file.pkr.hcl
