name: Node.js CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Print Node.js version
      run: node --version

    - name: Print npm version
      run: npm --version

    - name: Install dependencies
      run: npm install

    - name: Create webapp zip artifact
      run: zip -r /tmp/webapp.zip .

    - name: Upload repository artifact
      uses: actions/upload-artifact@v2
      with:
        name: webapp-artifact
        path: /tmp/webapp.zip
        
    - name: Initialize Packer
      run:  packer init packer/packer_file.pkr.hcl

    - name: Format Packer configuration
      run:  packer fmt packer/packer_file.pkr.hcl

    - name: Validate Packer configuration
      run:  packer validate packer/packer_file.pkr.hcl
    