name: Integration Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  integration-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          USER : ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          DATABASE : ${{ secrets.DATABASE }}
          HOST : ${{ secrets.HOST }}
          DIALECT : mysql
          AUTH_USER: ${{ secrets.AUTH_USER }}
          AUTH_PSWD:  ${{ secrets.AUTH_PSWD }}

        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Start mysql
        run: |
          sudo systemctl start mysql
          sudo systemctl enable mysql
          sudo systemctl status mysql

      - name: Wait for MySQL to start
        run: |
          echo "Waiting for MySQL to start"
          while ! mysqladmin ping -h 127.0.0.1 --silent; do
            sleep 1
          done
          echo "MySQL is up and running!"

      - name: Create DB
        run: |
          mysql -u root -p"${PASSWORD}" -h 127.0.0.1 --port 3306 -e "CREATE DATABASE IF NOT EXISTS healthDB;"
          mysql -u root -p"${PASSWORD}" -h 127.0.0.1 --port 3306 -e "USE healthDB;"
          mysql -h 127.0.0.1 -u root -p"${PASSWORD}" -e "GRANT ALL PRIVILEGES ON *.* TO '${USER}'@'%';"

      - name: Run tests
        run: npm run test:integration  
