name: Integration Tests

on:
  workflow_dispatch:
  push:
    branches:
       - main

jobs:
  integration-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}

        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Start mysql
        run: |
          sudo systemctl start mysql
          sudo systemctl enable mysql
          sudo systemctl status mysql

      - name: Wait for MySQL to start
        run: |
          echo "Waiting for MySQL to start"
          while ! mysqladmin ping -h 127.0.0.1 --silent; do
            sleep 1
          done
          echo "MySQL is up and running!"

      - name: Create DB
        run: mysql -h 127.0.0.1 --port 3306 -u root -proot -e 'CREATE DATABASE IF NOT EXISTS healthDB;'

      - name: Use Created Database
        run: mysql -h 127.0.0.1 --port 3306 -u root -proot -e 'USE healthDB;'


      - name: Run tests
        env:
          SQL_PSWD: "${{ secrets.SQL_PSWD }}"
          DATABASE: "healthDB"
          DIALECT: "mysql"
          SQL_USER : "root"
          HOST: 127.0.0.1
        run: npm run test:integration  
